/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_weizejian_myndk_MainActivity */

#ifndef _Included_com_example_weizejian_myndk_MainActivity
#define _Included_com_example_weizejian_myndk_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_weizejian_myndk_MainActivity
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_weizejian_myndk_MainActivity_getStringFromNative(JNIEnv *, jobject);
JNIEXPORT jstring JNICALL Java_com_example_weizejian_myndk_MainActivity_getMyname(JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
